apps/crud/models.py
from datetime import datetime

from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from apps.app import db, login_manager


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

    @property
    def password(self):
        raise AttributeError("無法加載")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def is_duplicate_email(self):
        return User.query.filter_by(email=self.email).first() is not None


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, length


class UserForm(FlaskForm):
    username = StringField(
        "使用者名稱",
        validators=[
            DataRequired(message="必須填寫使用者名稱"),
            length(max=30, message="請勿輸入超過30個字"),
        ],
    )

    email = StringField(
        "郵件位址",
        validators=[
            DataRequired(message="必須填寫郵件位址"),
            Email(message="請依照電子郵件的格式輸入"),
        ],
    )

    password = PasswordField("密碼", validators=[DataRequired(message="必須填寫密碼")])

    submit = SubmitField("提交表單")

apps/crud/views.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import login_required

from apps.app import db
from apps.crud.forms import UserForm
from apps.crud.models import User

crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)


@crud.route("/")
@login_required
def index():
    return render_template("crud/index.html")


@crud.route("/sql")
@login_required
def sql():
    db.session.query(User).all()
    return "Please check log"


@crud.route("/users/new", methods=["GET", "POST"])
@login_required
def create_user():
    form = UserForm()

    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )

        db.session.add(user)
        db.session.commit()

        return redirect(url_for("crud.users"))

    return render_template("crud/create.html", form=form)


@crud.route("/users")
@login_required
def users():
    users = User.query.all()
    return render_template("crud/index.html", users=users)


@crud.route("/users/<user_id>", methods=["GET", "POST"])
@login_required
def edit_user(user_id):
    form = UserForm()

    user = User.query.filter_by(id=user_id).first()

    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))

    return render_template("crud/edit.html", user=user, form=form)


@crud.route("/users/<user_id>/delete", methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css' ) }}" />
</head>

<body>
    <div>
        {% if current_user.is_authenticated %}
        <p>
            <span>{{ current_user.username }}</span> -
            <span><a href="{{ url_for('auth.logout') }}"> 登出 </a></span>
        </p>
        {% endif %}
    </div>
    {% block content %}{% endblock %}
</body>

</html>

apps/crud/templates/crud/create.html
{% extends "crud/base.html" %}
{% block title %}新增使用者{% endblock %}
{% block content %}

<h2>新增使用者</h2>
<form action="{{ url_for('crud.create_user') }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }}
        {{ form.username(placeholder="使用者名稱") }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.email.label }}
        {{ form.email(placeholder="郵件位址") }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.password.label }}
        {{ form.password(placeholder="密碼") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

apps/crud/templates/crud/edit.html
{% extends "crud/base.html" %}
{% block title %}編輯使用者{% endblock %}
{% block content %}

<h2>編輯使用者</h2>
<form action="{{ url_for('crud.edit_user', user_id=user.id) }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }} {{ form.username(placeholder="使用者名稱",
        value=user.username) }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.email.label }} {{ form.email(placeholder="郵件位址",
        value=user.email) }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.password.label }} {{ form.password(placeholder="密碼") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p><input type="submit" value="修改" /></p>
</form>

<form action="{{ url_for('crud.delete_user', user_id=user.id) }}" method="POST">
    {{ form.csrf_token }}
    <input type="submit" value="刪除">
</form>
{% endblock %}

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title %}使用者列表{% endblock %}
{% block content %}

<h2>使用者列表</h2>
<a href="{{ url_for('crud.create_user') }}"> 新增使用者 </a>

<table>
    <tr>
        <th>使用者ID</th>
        <th>使用者名稱</th>
        <th>郵件位址</th>
    </tr>
    {% for user in users %}
    <tr>
        <td>
            <a href="{{ url_for('crud.edit_user', user_id=user.id) }}">{{ user.id }}</a>
        </td>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}